"""
This SConscript contains some project specifics.
"""
# Get the passed in environment.
Import('env')

# Configure the builders. This is all we're doing here for this case.
env = SConscript('builders.SConscript', 'env')

# Needed apparently on lx06 at IC
import os.path
env['ENV']['TEXMFHOME'] = os.path.join(os.environ['HOME'],'texmf')

# Pass back the modified environment.
Return('env')
